baseURL = 'https://mtarnawa.org/'
languageCode = 'en-us'
title = 'Mateusz Tarnawa'
theme = "black-and-light"

author = "Mateusz Tarnawa"
canonifyurls = true

pygmentsUseClassic            = true
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses            = true

[markup.goldmark.renderer]
   unsafe = true

[services]
  [services.disqus]
    shortname = 'mtarnawa'

[params]
  sitename = "Mateusz Tarnawa"
  description = "Personal blog by Mateusz Tarnawa — writing about film, music, photography, books and software."
  disableWebFonts = false
  dateFormat = "2 January 2006"
  [params.services]
    [params.services.umami_analytics]
      id = '8b2f4a06-ecf4-45c4-838f-5c978ca43f68'
      script_url = 'https://cloud.umami.is/script.js'


[[menu.main]]
    name = "Blog"
    url  = "/"
[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    name = "Flickr"
    url  = "https://www.flickr.com/photos/204114481@N08/"
[[menu.main]]
    name = "Linkedin"
    url  = "https://www.linkedin.com/in/mtarnawa/"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/mtarnawa"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
[module]
  [[module.imports]]
    path = 'github.com/hugomods/umami-analytics'
